---
driver:
  name: docker

platforms:
  # pip cache cannot be shared due to multiple bugs:
  # - python2 cache incompatible with python3 https://github.com/pypa/pip/issues/5250
  # - concurrency issues

  # Temporary disabled as it fails to install cython -- not really our fault
  # - name: alpine
  #   hostname: alpine
  #   image: pycontribs/alpine:latest
  #   pre_build_image: true
  #   volumes:
  #     - /root/.cache/pip-alpine:/root/.cache/pip:rw

  - name: centos8
    hostname: centos8
    image: pycontribs/centos:8
    pre_build_image: true
    volumes:
      - /root/.cache/pip-centos8:/root/.cache/pip:rw

  - name: debian
    hostname: debian
    image: pycontribs/debian:latest
    pre_build_image: true
    volumes:
      - /root/.cache/pip-debian:/root/.cache/pip:rw

  - name: fedora
    hostname: fedora
    image: pycontribs/fedora:latest
    pre_build_image: true
    volumes:
      - /root/.cache/pip-fedora:/root/.cache/pip:rw

  - name: opensuse
    hostname: opensuse
    image: pycontribs/opensuse:latest
    pre_build_image: true
    volumes:
      - /root/.cache/pip-opensuse:/root/.cache/pip:rw

  # - name: rhel8
  #   hostname: rhel8
  #   image: ubi8/python-36
  #   registry:
  #     url: registry.access.redhat.com
  #   dockerfile: ../Dockerfile.j2
  #   volumes:
  #     - /root/.cache/pip-rhel8:/root/.cache/pip:rw

  - name: ubuntu
    hostname: ubuntu
    image: pycontribs/ubuntu:latest
    pre_build_image: true
    volumes:
      - /root/.cache/pip-ubuntu:/root/.cache/pip:rw

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      interpreter_python: auto
      verbosity: 1

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - destroy
